async function saveModal(t){let error;if(t==='due')({error}=await db.from('dues').insert({site_id:SITE,unit_id:+$('#mUnit').value,period:$('#mPeriod').value+'-01',amount:+$('#mAmount').value,due_date:$('#mDue').value,created_by:profile.id}));if(t==='budget')({error}=await db.from('budgets').insert({site_id:SITE,year:new Date().getFullYear(),name:$('#mName').value,planned:+$('#mPlanned').value,spent:+$('#mSpent').value,created_by:profile.id}));if(t==='notice')({error}=await db.from('announcements').insert({site_id:SITE,title:$('#mTitle').value,body:$('#mBody').value,audience:$('#mAudience').value,created_by:profile.id}));if(t==='doc'){const f=$('#mFile').files[0];if(!f)return toast('Dosya seçin.');if(f.size>52428800)return toast('Dosya 50 MB sınırını aşıyor.','error');const path=Date.now()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');let r=await db.storage.from('site-documents').upload(path,f);error=r.error;if(!error)({error}=await db.from('documents').insert({site_id:SITE,name:f.name,storage_path:path,mime_type:f.type,size_bytes:f.size,category:$('#mCategory').value,uploaded_by:profile.id}))}if(error)return toast(error.message);$('#modalRoot').innerHTML='';toast('Kaydedildi.');await loadAll()}
async function togglePaid(id){const d=data.dues.find(x=>x.id===id),paid=d.status!=='paid';const {error}=await db.from('dues').update({status:paid?'paid':'unpaid',paid_at:paid?new Date().toISOString():null}).eq('id',id);if(error)toast(error.message);else loadAll()}
function remind(id){const d=data.dues.find(x=>x.id===id),p=occupant(d.unit_id),text=`Merhaba ${p.full_name}, ${new Date(d.period).toLocaleDateString('tr-TR',{month:'long',year:'numeric'})} dönemine ait ${money(d.amount)} aidatınız ödenmemiş görünüyor. Son ödeme: ${new Date(d.due_date).toLocaleDateString('tr-TR')}. Asrav Sitesi Yönetimi`;$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>Hatırlatma</h3><button class="close" data-close>×</button></div><div class="modal-body"><textarea id="msg" style="width:100%;min-height:140px">${esc(text)}</textarea></div><div class="modal-foot"><button class="ghost" id="mail">E-posta</button><button class="ghost" id="sms">SMS</button><button class="primary" id="wa">WhatsApp</button></div></div></div>`;const log=c=>db.from('notification_logs').insert({site_id:SITE,due_id:id,recipient_profile_id:p.id,channel:c,sent_by:profile.id});$('[data-close]').onclick=()=>$('#modalRoot').innerHTML='';$('#mail').onclick=()=>{log('email');location.href=`mailto:${p.email}?subject=Aidat hatırlatması&body=${encodeURIComponent(text)}`};$('#sms').onclick=()=>{log('sms');location.href=`sms:+${p.phone}?body=${encodeURIComponent(text)}`};$('#wa').onclick=()=>{log('whatsapp');open('https://wa.me/'+String(p.phone||'').replace(/\D/g,'')+'?text='+encodeURIComponent(text),'_blank')}}
async function openDoc(id){const d=data.documents.find(x=>x.id===id),{data:r,error}=await db.storage.from('site-documents').createSignedUrl(d.storage_path,120);if(error)toast(error.message);else open(r.signedUrl,'_blank')}
async function deleteDoc(id){if(!confirm('Belge silinsin mi?'))return;const d=data.documents.find(x=>x.id===id);await db.storage.from('site-documents').remove([d.storage_path]);const {error}=await db.from('documents').delete().eq('id',id);if(error)toast(error.message);else loadAll()}
async function saveProfile(id){const role=$('#r-'+id).value,unitId=$('#u-'+id).value||null,{error}=await db.rpc('set_profile_access',{target_user_id:id,target_role:role,target_unit_id:unitId?+unitId:null});if(error)toast(error.message,'error');else{toast('Kullanıcının rolü ve dairesi güncellendi.');loadAll()}}
async function saveRolePermissions(role){const permissions={...permissionMap[role]};$$(`[data-role-perm="${role}"]`).forEach(x=>permissions[x.dataset.key]=x.checked);['dues','budgets','documents','announcements'].forEach(k=>{if(permissions[k+'_manage'])permissions[k+'_view']=true});permissions.roles_manage=false;permissions.residents_manage=false;const {error}=await db.rpc('set_role_permissions',{target_role:role,new_permissions:permissions});if(error)toast(error.message,'error');else{toast(roles[role]+' yetkileri kaydedildi.');await loadAll()}}
let authNoticeShown=false;
function showAuthNotice(){if(authNoticeShown)return;if(authError){const expired=authErrorCode==='otp_expired'||String(authError).toLowerCase().includes('expired');toast(expired?'Doğrulama bağlantısının süresi dolmuş. Yeni bir doğrulama e-postası isteyin.':'E-posta doğrulanamadı: '+decodeURIComponent(authError),'error',9000);$('#resendConfirm').classList.remove('hidden');authNoticeShown=true}else if(authCallbackSuccess){toast('E-posta adresiniz başarıyla doğrulandı. Artık hesabınızı kullanabilirsiniz.','success',8000);authNoticeShown=true}if(authNoticeShown)setTimeout(()=>history.replaceState({},'',location.pathname),1200)}
$('#resendConfirm').onclick=async()=>{const email=$('#loginEmail').value.trim();if(!email)return toast('Önce e-posta adresinizi yazın.','error');const {error}=await db.auth.resend({type:'signup',email,options:{emailRedirectTo:AUTH_REDIRECT}});if(error)toast(error.message,'error');else toast('Yeni doğrulama e-postası gönderildi. Gelen kutunuzu kontrol edin.','success',7000)};
db.auth.onAuthStateChange((_e,s)=>{boot(s);setTimeout(showAuthNotice,350)});db.auth.getSession().then(({data:{session:s}})=>{boot(s);setTimeout(showAuthNotice,500)});
