(()=>{
const roleOrder=['admin','manager','owner','tenant','resident'],roleText={admin:'Admin',manager:'Yönetici',owner:'Ev Sahibi',tenant:'Kiracı',resident:'Atama Bekliyor'};
const calc=d=>{const a=Math.max(0,+d.amount||0),o=Math.max(0,+d.previous_debt||0),cp=d.current_due_paid===true||(d.current_due_paid==null&&d.status==='paid'),op=Math.max(0,Math.min(o,d.previous_debt_paid_amount==null?(d.previous_debt_paid?o:0):+d.previous_debt_paid_amount||0)),paid=(cp?a:0)+op,total=a+o;if(total<=0||paid>=total)return'paid';if(paid>0)return'pending';const x=d.due_date?new Date(String(d.due_date).slice(0,10)+'T23:59:59'):null;return x&&x<new Date()?'late':'unpaid'};
function lockStatuses(){if(page!=='dues')return;const table=$('#rows');if(!table)return;table.querySelectorAll('tbody tr:not(.missing-due-row)').forEach(tr=>{const period=(tr.dataset.year||'')+'-'+(tr.dataset.month||''),d=(data.dues||[]).find(x=>String(x.unit_id)===String(tr.dataset.unit)&&String(x.period||'').slice(0,7)===period);if(!d)return;tr.dataset.dueId=String(d.id);const s=calc(d);if(tr.dataset.finalStatus!==s)tr.dataset.finalStatus=s;tr.dataset.status=s==='paid'?'paid':s==='pending'?'pending':'unpaid'});typeof applyDueFilters==='function'&&applyDueFilters()}
const values=p=>Array.isArray(p?.roles)&&p.roles.length?p.roles:[p?.role||p?.resident_role||'resident'];
function checks(id,selected,kind){return'<div class="multi-role-box" data-role-kind="'+kind+'" data-role-id="'+id+'">'+roleOrder.map(r=>'<label class="multi-role-choice '+r+'"><input type="checkbox" value="'+r+'" '+(selected.includes(r)?'checked':'')+'><span>'+roleText[r]+'</span></label>').join('')+'</div>'}
function chosen(box){const a=[...box.querySelectorAll('input:checked')].map(x=>x.value);return a.length?a:['resident']}
async function saveProfileRoles(id,box){const p=(data.profiles||[]).find(x=>x.id===id),r=await db.rpc('set_profile_roles',{target_user_id:id,target_roles:chosen(box),target_unit_id:p?.unit_id||null});if(r.error)return toast('Rol güncellenemedi: '+r.error.message,'error');toast('Roller güncellendi. En yetkili rol uygulanıyor.');await loadAll()}
async function saveResidentRoles(kind,id,box){let r;if(kind==='profile'){const p=(data.profiles||[]).find(x=>x.id===id);r=await db.rpc('set_profile_roles',{target_user_id:id,target_roles:chosen(box),target_unit_id:p?.unit_id||null})}else r=await db.rpc('set_resident_contact_roles',{p_contact_id:+id,p_roles:chosen(box)});if(r.error)return toast('Rol güncellenemedi: '+r.error.message,'error');toast('Roller güncellendi. En yetkili rol uygulanıyor.');if(kind==='profile')await loadAll();else{const c=(data.residentContacts||[]).find(x=>String(x.id)===String(id));if(c){c.roles=chosen(box);c.resident_role=roleOrder.find(x=>c.roles.includes(x))||'resident'}render()}}
function patchAdminRoles(){if(page!=='admin'||profile?.role!=='admin')return;$$('[data-profile]').forEach(button=>{const id=button.dataset.profile,p=(data.profiles||[]).find(x=>x.id===id),tr=button.closest('tr'),select=$('#r-'+id);if(!p||!tr||!select)return;const cell=select.closest('td');if(!cell.querySelector('.multi-role-box')){select.classList.add('role-select-hidden');cell.insertAdjacentHTML('afterbegin',checks(id,values(p),'profile'));}button.textContent='Rolleri kaydet';button.onclick=()=>saveProfileRoles(id,cell.querySelector('.multi-role-box'))})}
function patchResidentRoles(){if(page!=='residentContacts')return;$$('[data-save-resident-role]').forEach(old=>{const key=old.dataset.saveResidentRole,[kind,...parts]=key.split('-'),id=parts.join('-'),control=old.closest('.resident-role-control');if(!control||control.querySelector('.multi-role-box'))return;const p=kind==='profile'?(data.profiles||[]).find(x=>x.id===id):(data.residentContacts||[]).find(x=>String(x.id)===String(id));control.innerHTML=checks(id,values(p),kind)+'<button class="role-multi-save">Kaydet</button>';control.classList.add('resident-role-multi');control.querySelector('.role-multi-save').onclick=()=>saveResidentRoles(kind,id,control.querySelector('.multi-role-box'))})}
function clarifyPassword(){const m=$('.password-admin-modal');if(!m||m.dataset.separatedActions)return;m.dataset.separatedActions='1';const l=m.querySelector('label');if(l&&/geçici şifre/i.test(l.textContent))l.textContent='Geçici şifre';if($('#setAdminPassword'))$('#setAdminPassword').textContent='Geçici şifreyi kaydet';if($('#sendPasswordReset'))$('#sendPasswordReset').textContent='Yeni şifre belirleme bağlantısı gönder'}
function applyFinal(){lockStatuses();patchAdminRoles();patchResidentRoles();clarifyPassword()}
const oldRender=render;render=()=>{const r=oldRender();applyFinal();return r};let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(applyFinal,80)}).observe(document.body,{childList:true,subtree:true});setInterval(lockStatuses,1000);
const style=document.createElement('style');style.textContent=`#rows td:nth-child(7){position:relative;width:176px!important;min-width:176px!important;max-width:176px!important}#rows tr[data-final-status] td:nth-child(7)>*{visibility:hidden!important}#rows tr[data-final-status] td:nth-child(7):after{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:650;white-space:nowrap}#rows tr[data-final-status=paid] td:nth-child(7):after{content:'● Ödendi';background:var(--green2);color:var(--green)}#rows tr[data-final-status=pending] td:nth-child(7):after{content:'● Kısmi ödeme';background:var(--orange2);color:var(--orange)}#rows tr[data-final-status=late] td:nth-child(7):after{content:'● Gecikmiş / Ödenmedi';background:var(--red2);color:var(--red)}#rows tr[data-final-status=unpaid] td:nth-child(7):after{content:'● Ödenmedi';background:var(--red2);color:var(--red)}.role-select-hidden{display:none!important}.multi-role-box{display:flex;flex-wrap:wrap;gap:5px;min-width:210px}.multi-role-choice{display:inline-flex!important;align-items:center!important;gap:4px!important;margin:0!important;padding:4px 7px!important;border:1px solid #cfddda;border-radius:7px;background:#f8fbfa;font-size:10px!important;font-weight:750;white-space:nowrap}.multi-role-choice input{width:14px!important;height:14px!important;margin:0!important;accent-color:#0492c2}.multi-role-choice.admin{border-color:#e3b0a8;background:#fff4f2}.multi-role-choice.manager{border-color:#abd3df;background:#f0f9fc}.multi-role-choice.owner{border-color:#acd8c8;background:#f0faf6}.resident-role-multi{display:grid!important;grid-template-columns:1fr auto!important;gap:6px!important;align-items:center!important}.resident-role-multi .multi-role-box{min-width:260px}.role-multi-save{min-height:30px;border:0;border-radius:7px;padding:5px 9px;background:#0492c2;color:#fff;font-size:10px;font-weight:800}@media(max-width:760px){.multi-role-box{min-width:190px}.resident-role-multi .multi-role-box{min-width:240px}.multi-role-choice{font-size:9px!important;padding:3px 5px!important}}`;document.head.appendChild(style);applyFinal()
})();
