const trMonths={ocak:1,subat:2,mart:3,nisan:4,mayis:5,haziran:6,temmuz:7,agustos:8,eylul:9,ekim:10,kasim:11,aralik:12};
const norm=s=>String(s??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]/g,'');
const iso=d=>d&&d instanceof Date&&!isNaN(d)?d.toISOString().slice(0,10):'';
function parseDateValue(v){if(v instanceof Date)return iso(v);if(typeof v==='number'&&window.XLSX){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const s=String(v||'').trim();let m=s.match(/(20\d{2})[-/.](\d{1,2})(?:[-/.](\d{1,2}))?/);if(m)return `${m[1]}-${m[2].padStart(2,'0')}-${(m[3]||'01').padStart(2,'0')}`;m=s.match(/(\d{1,2})[-/.](\d{1,2})[-/.](20\d{2})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const n=norm(s);for(const [name,month] of Object.entries(trMonths)){if(n.includes(name)){const y=(s.match(/20\d{2}/)||[new Date().getFullYear()])[0];return `${y}-${String(month).padStart(2,'0')}-01`}}return ''}
function monthStart(v){const d=parseDateValue(v);return d?d.slice(0,7)+'-01':''}
function parseAmount(v){if(typeof v==='number')return Math.round(v*100)/100;let s=String(v||'').replace(/[^0-9,.-]/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');const n=Number(s);return Number.isFinite(n)?n:null}
function findUnit(v){const text=norm(v),digits=String(v||'').match(/\d+/)?.[0];return data.units.find(u=>norm(u.label)===text||(digits&&String(u.label).match(/\d+/)?.[0]===digits))?.id||null}
function findUnitInText(text){const n=norm(text);for(const u of data.units){const no=String(u.label).match(/\d+/)?.[0];if(new RegExp(`(?:daire|bolum|no)0*${no}(?:[^0-9]|$)`).test(n))return u.id}for(const p of data.profiles){if(p.unit_id&&p.full_name&&n.includes(norm(p.full_name)))return p.unit_id}return null}
function rowValue(obj,aliases){for(const [k,v] of Object.entries(obj)){const nk=norm(k);if(aliases.some(a=>nk===a||nk.includes(a)))return v}return ''}
function rowStatus(v,paidDefault=false){const n=norm(v);return paidDefault||n.includes('odendi')||n.includes('paid')||n.includes('tahsil')?'paid':n.includes('bekle')?'pending':'unpaid'}
function normalizeSheetRows(raw){return raw.map((o,i)=>{const unitRaw=rowValue(o,['daire','bagimsizbolum','bolum','unit','kapino','no']);const periodRaw=rowValue(o,['donem','ay','aidatayi','period','tarih']);const dueRaw=rowValue(o,['sonodeme','vade','duedate']);const amountRaw=rowValue(o,['aidat','tutar','borc','amount','toplam']);const statusRaw=rowValue(o,['durum','odeme','status']);const unit_id=findUnit(unitRaw),period=monthStart(periodRaw),amount=parseAmount(amountRaw);return{unit_id,unit_label:String(unitRaw||''),period,amount,due_date:parseDateValue(dueRaw)||period,status:rowStatus(statusRaw),confidence:(unit_id?35:0)+(period?30:0)+(amount!==null?30:0)+(statusRaw!==''?5:0),source:`Excel satırı ${i+2}`}}).filter(r=>r.amount!==null||r.unit_label||r.period).slice(0,500)}
function parseTextRows(text,paidDefault=false){const lines=String(text||'').split(/\n+/).map(x=>x.trim()).filter(x=>x.length>3),rows=[];for(const line of lines){const amountMatch=line.match(/(?:tutar|toplam|aidat|islem tutari)\s*[:=-]?\s*([\d.]+(?:,\d{1,2})?)/i)||line.match(/([\d.]+,\d{2})\s*(?:tl|try|₺)?/i);const amount=parseAmount(amountMatch?.[1]);if(amount===null)continue;const unit_id=findUnitInText(line)||findUnitInText(text);const date=parseDateValue(line)||parseDateValue(text);const period=monthStart(date||new Date());rows.push({unit_id,unit_label:unit_id?unit(unit_id):'',period,amount,due_date:date||period,status:rowStatus(line,paidDefault),confidence:(unit_id?40:0)+(date?25:10)+30,source:line.slice(0,180)})}const seen=new Set();return rows.filter(r=>{const k=[r.unit_id,r.period,r.amount,r.status].join('|');if(seen.has(k))return false;seen.add(k);return true}).slice(0,200)}
async function extractDocument(file){const ext=(file.name.split('.').pop()||'').toLowerCase();if(['xlsx','xls','xlsm','xlsb','csv','ods'].includes(ext)){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});let rows=[];for(const name of wb.SheetNames)rows.push(...normalizeSheetRows(XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:true})));return{kind:'aidat_listesi',rows}}
if(ext==='pdf'){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();text+='\n'+c.items.map(x=>x.str).join(' ')}return{kind:norm(text).includes('dekont')?'dekont':'pdf',rows:parseTextRows(text,norm(text).includes('dekont')),text:text.slice(0,4000)}}
if(file.type.startsWith('image/')){const r=await Tesseract.recognize(file,'tur+eng');const text=r.data.text||'';return{kind:'dekont',rows:parseTextRows(text,true),text:text.slice(0,4000)}}
if(['txt','tsv'].includes(ext)||file.type.startsWith('text/')){const text=await file.text();return{kind:'metin',rows:parseTextRows(text,false),text:text.slice(0,4000)}}
return{kind:'diger',rows:[]}}
