(()=>{
const labels={AUTH:'Kimlik doğrulama',PERMISSION:'Yetki',VALIDATION:'Doğrulama',NETWORK:'Bağlantı',SERVER:'Sunucu',STORAGE:'Dosya',QUOTA:'Kota',FRONTEND:'Uygulama',DATA:'Veri'};
let errors={page:1,total:0,rows:[],search:'',category:'',code:'',from:'',to:''};
function shell(){return `<section class="panel error-panel app-errors-2583" id="appErrorLogs2583"><div class="panel-head"><div><h3>Son Uygulama Hataları</h3><p>Tüm uygulama hataları filtrelenebilir. Her sayfada en fazla 100 kayıt gösterilir.</p></div></div><div class="error-filter-2583"><input id="erSearch2583" placeholder="Kullanıcı e-postası, teknik özet veya build" value="${esc(errors.search)}"><select id="erCategory2583"><option value="">Tüm kategoriler</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${errors.category===k?'selected':''}>${v}</option>`).join('')}</select><input id="erCode2583" placeholder="Hata kodu" value="${esc(errors.code)}"><input id="erFrom2583" type="date" value="${esc(errors.from)}"><input id="erTo2583" type="date" value="${esc(errors.to)}"><button class="primary" id="erApply2583">Filtrele</button><button class="ghost" id="erClear2583">Temizle</button></div><div id="erResults2583"><div class="logs-loading-2562">Hata kayıtları yükleniyor…</div></div></section>`}
function results(){if(!errors.rows.length)return '<div class="empty">Filtreye uygun uygulama hatası bulunamadı.</div>';const pages=Math.max(1,Math.ceil(errors.total/100)),first=(errors.page-1)*100+1,last=Math.min(errors.page*100,errors.total),nums=[];for(let p=Math.max(1,errors.page-2);p<=Math.min(pages,errors.page+2);p++)nums.push(`<button data-er-page="${p}" class="${p===errors.page?'active':''}">${p}</button>`);return `<div class="logs-count-2562">Toplam <b>${errors.total}</b> kalıcı hata kaydı · ${first}–${last} arası gösteriliyor</div><div class="table-wrap"><table class="error-table-2583"><thead><tr><th>Kod</th><th>Kategori</th><th>Kullanıcı</th><th>Tarih ve Saat</th><th>Build</th><th>Teknik Özet</th></tr></thead><tbody>${errors.rows.map(r=>`<tr><td><b>${esc(r.error_code||'—')}</b></td><td>${esc(labels[r.category]||r.category||'—')}</td><td>${esc(r.user_email||'—')}</td><td>${new Date(r.created_at).toLocaleString('tr-TR')}</td><td>${esc(r.app_build||'—')}</td><td><small title="${esc(r.message||'')}">${esc((r.message||'—').slice(0,220))}</small></td></tr>`).join('')}</tbody></table></div><div class="logs-pages-2562"><button data-er-page="${errors.page-1}" ${errors.page<=1?'disabled':''}>← Önceki</button>${nums.join('')}<button data-er-page="${errors.page+1}" ${errors.page>=pages?'disabled':''}>Sonraki →</button><span>Sayfa ${errors.page} / ${pages}</span></div>`}
async function loadErrors(){const box=$('#erResults2583');if(!box)return;box.innerHTML='<div class="logs-loading-2562">Hata kayıtları yükleniyor…</div>';const r=await db.rpc('get_application_error_logs_page',{p_page:errors.page,p_page_size:100,p_search:errors.search||null,p_category:errors.category||null,p_error_code:errors.code||null,p_date_from:errors.from||null,p_date_to:errors.to||null});if(r.error){box.innerHTML='<div class="empty">Hata kayıtları yüklenemedi: '+esc(r.error.message)+'</div>';return}errors.rows=r.data||[];errors.total=+(errors.rows[0]?.total_count||0);box.innerHTML=results();$$('[data-er-page]').forEach(b=>b.onclick=()=>{const p=+b.dataset.erPage,pages=Math.max(1,Math.ceil(errors.total/100));if(p<1||p>pages||p===errors.page)return;errors.page=p;loadErrors()})}
function bind(){const apply=$('#erApply2583'),clear=$('#erClear2583'),search=$('#erSearch2583');if(!apply)return;apply.onclick=()=>{errors.search=search.value.trim();errors.category=$('#erCategory2583').value;errors.code=$('#erCode2583').value.trim().toUpperCase();errors.from=$('#erFrom2583').value;errors.to=$('#erTo2583').value;errors.page=1;loadErrors()};clear.onclick=()=>{errors={page:1,total:0,rows:[],search:'',category:'',code:'',from:'',to:''};$('#appErrorLogs2583').remove();mount()};search.onkeydown=e=>{if(e.key==='Enter')apply.click()};$('#erCode2583').onkeydown=e=>{if(e.key==='Enter')apply.click()}}
function mount(){if(page!=='systemHealth'||profile?.role!=='admin')return;const host=$('#healthContent');if(!host)return;const old=host.querySelector('.error-panel:not(#appErrorLogs2583)');if(old)old.remove();if($('#appErrorLogs2583')||!host.querySelector('.health-bottom'))return;host.insertAdjacentHTML('beforeend',shell());bind();loadErrors()}
const oldRender=render;render=function(){const r=oldRender();setTimeout(mount,0);return r};let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(mount,35)}).observe($('#content'),{childList:true,subtree:true});
const style=document.createElement('style');style.textContent=`.app-errors-2583{margin-top:14px}.app-errors-2583 p{margin:3px 0 0;color:#365860;font-weight:620}.error-filter-2583{display:grid;grid-template-columns:minmax(220px,1fr) 150px 125px 135px 135px auto auto;gap:7px;padding:13px;border-top:1px solid var(--line)}.error-table-2583{min-width:1000px}.app-errors-2583 .logs-pages-2562 button.active{background:#0492c2;color:#fff}@media(max-width:1000px){.error-filter-2583{grid-template-columns:1fr 1fr}.error-filter-2583 input:first-child{grid-column:1/3}}`;document.head.appendChild(style);mount();
})();
