(()=>{const form=document.querySelector('#loginForm');if(!form)return;form.addEventListener('submit',e=>{const email=document.querySelector('#loginEmail'),pass=document.querySelector('#loginPass');if(!email||!pass||!email.value.trim()||pass.value.length)return;e.preventDefault();e.stopImmediatePropagation();showAuthMessage(signup?'Lütfen bir şifre oluşturun.':'Lütfen şifrenizi girin.','error','AUTH-VAL-PASSWORD')},true)})();
(()=>{const form=document.querySelector('#loginForm');if(!form||typeof db==='undefined')return;
const submit=document.querySelector('#authSubmit'),panel=document.createElement('div');panel.id='authMessage';panel.className='auth-message hidden';panel.setAttribute('role','alert');panel.setAttribute('aria-live','assertive');panel.setAttribute('aria-atomic','true');submit.parentNode.insertBefore(panel,submit);
const style=document.createElement('style');style.textContent='.auth-message{display:block;margin:0 0 12px;padding:12px 14px;border:1px solid;border-radius:10px;font-size:13px;font-weight:700;line-height:1.45;white-space:pre-wrap}.auth-message.hidden{display:none}.auth-message.error{border-color:#d98b8b;background:#fff0f0;color:#872828}.auth-message.success{border-color:#83bea2;background:#edf9f3;color:#17633e}.auth-message.info{border-color:#8bb7ca;background:#eef8fc;color:#235a72}';document.head.appendChild(style);
window.showAuthMessage=(message,type='error',code='AUTH-UNKNOWN')=>{const text=String(message||'İşlem tamamlanamadı. Lütfen tekrar deneyin.');panel.textContent=text;panel.className='auth-message '+type;panel.dataset.code=code;console[type==='error'?'warn':'info'](JSON.stringify({event:'auth_message',code,message:text,timestamp:new Date().toISOString()}));if(typeof toast==='function')toast(text,type==='error'?'error':'success',7000);panel.scrollIntoView({behavior:'smooth',block:'nearest'});return false};
const clearMessage=()=>{panel.textContent='';panel.className='auth-message hidden';delete panel.dataset.code};form.querySelectorAll('input').forEach(input=>input.addEventListener('input',clearMessage));document.querySelector('#authToggle')?.addEventListener('click',clearMessage);
const focusField=field=>{const map={email:'#loginEmail',password:'#loginPass',full_name:'#loginName',phone:'#signupPhone'};const el=document.querySelector(map[field]);if(el){el.setAttribute('aria-invalid','true');el.focus()}};
const turkishLoginError=error=>{const low=String(error?.message||'').toLowerCase(),code=String(error?.code||'');if(low.includes('invalid login credentials')||code==='invalid_credentials')return['E-posta adresi veya şifre hatalı.','AUTH-LOGIN-INVALID'];if(low.includes('email not confirmed')||code==='email_not_confirmed')return['E-posta adresiniz henüz doğrulanmamış. Lütfen doğrulama bağlantısını açın.','AUTH-LOGIN-NOT-CONFIRMED'];if(low.includes('rate limit')||code.includes('rate_limit'))return['Çok fazla giriş denemesi yapıldı. Lütfen bir süre bekleyip tekrar deneyin.','AUTH-LOGIN-LIMIT'];if(low.includes('network')||low.includes('fetch'))return['Sunucuya bağlanılamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.','AUTH-NETWORK'];return['Giriş işlemi tamamlanamadı. Lütfen tekrar deneyin.','AUTH-LOGIN-UNKNOWN']};
async function functionError(result){if(result?.data?.message)return{message:result.data.message,code:result.data.error_code||'REG-UNKNOWN',field:result.data.field};const response=result?.error?.context;if(response&&typeof response.clone==='function'){try{const body=await response.clone().json();if(body?.message)return{message:body.message,code:body.error_code||'REG-UNKNOWN',field:body.field}}catch{}}return{message:'Kayıt sunucusuna bağlanılamadı. İnternet bağlantınızı kontrol edip tekrar deneyin.',code:'REG-NETWORK'}}
form.onsubmit=async e=>{e.preventDefault();clearMessage();form.querySelectorAll('[aria-invalid="true"]').forEach(x=>x.removeAttribute('aria-invalid'));const email=document.querySelector('#loginEmail').value.trim().toLowerCase(),password=document.querySelector('#loginPass').value,name=document.querySelector('#loginName').value.trim(),phone=normalizeContactPhone(document.querySelector('#signupPhone').value);
if(!email)return showAuthMessage('E-posta adresinizi girin.','error','AUTH-VAL-EMAIL-EMPTY');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){focusField('email');return showAuthMessage('Geçerli bir e-posta adresi girin. Örnek: adiniz@example.com','error','AUTH-VAL-EMAIL')}
if(!password){focusField('password');return showAuthMessage(signup?'Lütfen bir şifre oluşturun.':'Lütfen şifrenizi girin.','error','AUTH-VAL-PASSWORD-EMPTY')}
if(password.length<(signup?8:6)){focusField('password');return showAuthMessage(signup?'Şifre en az 8 karakter olmalıdır.':'Şifre en az 6 karakter olmalıdır.','error','AUTH-VAL-PASSWORD-SHORT')}
if(signup&&password.length>128){focusField('password');return showAuthMessage('Şifre en fazla 128 karakter olabilir.','error','AUTH-VAL-PASSWORD-LONG')}
if(signup&&name.length<2){focusField('full_name');return showAuthMessage('Ad soyad en az 2 karakter olmalıdır.','error','AUTH-VAL-NAME')}
if(signup&&!phone){focusField('phone');return showAuthMessage('Geçerli bir telefon numarası girin. Örnek: 05XX XXX XX XX.','error','AUTH-VAL-PHONE')}
submit.disabled=true;submit.setAttribute('aria-busy','true');try{if(signup){const result=await db.functions.invoke('register-resident',{body:{email,password,full_name:name,phone}});if(result?.error||result?.data?.ok===false){const issue=await functionError(result);focusField(issue.field);return showAuthMessage(issue.message,'error',issue.code)}showAuthMessage(result?.data?.message||'Hesabınız oluşturuldu. Yönetici yetkilendirmesinden sonra giriş yapabilirsiniz.','success',result?.data?.code||'REG-SUCCESS');setAuthMode(false);document.querySelector('#loginPass').value='';document.querySelector('#loginName').value='';document.querySelector('#signupPhone').value='';return}
const {error}=await db.auth.signInWithPassword({email,password});if(error){const [message,code]=turkishLoginError(error);return showAuthMessage(message,'error',code)}localStorage.setItem('asravLoginEmail',email);console.info(JSON.stringify({event:'login_success',code:'AUTH-LOGIN-SUCCESS',message:'Kullanıcı başarıyla giriş yaptı.',timestamp:new Date().toISOString()}))}catch(error){console.error(JSON.stringify({event:'auth_unexpected_error',code:'AUTH-SRV-999',message:'Kimlik doğrulama sırasında beklenmeyen hata oluştu.',error_type:error?.name||'unknown',timestamp:new Date().toISOString()}));showAuthMessage(signup?'Kayıt sırasında beklenmeyen bir hata oluştu. Lütfen birkaç dakika sonra tekrar deneyin.':'Giriş sırasında beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.','error','AUTH-SRV-999')}finally{submit.disabled=false;submit.removeAttribute('aria-busy')}}})();
