(()=>{
const sidebar=$('#sidebar'),shade=$('#mobileDrawerShade'),more=$('#mobileMore'),menu=$('#menuBtn');
function openDrawer(){if(innerWidth>760)return;sidebar?.classList.add('open');shade?.classList.add('show');document.body.classList.add('mobile-drawer-open');menu?.setAttribute('aria-expanded','true');sidebar?.setAttribute('aria-hidden','false');sidebar?.scrollTo({top:0,behavior:'instant'})}
function closeDrawer(){sidebar?.classList.remove('open');shade?.classList.remove('show');document.body.classList.remove('mobile-drawer-open');menu?.setAttribute('aria-expanded','false');sidebar?.setAttribute('aria-hidden',innerWidth<=760?'true':'false')}
if(sidebar&&!$('#mobileDrawerClose')){const brand=sidebar.querySelector('.brand');brand?.insertAdjacentHTML('beforeend','<button type="button" id="mobileDrawerClose" aria-label="Menüyü kapat">×</button>')}
if(more)more.onclick=e=>{e.preventDefault();e.stopPropagation();sidebar?.classList.contains('open')?closeDrawer():openDrawer()};
if(menu)menu.onclick=e=>{e.preventDefault();e.stopPropagation();sidebar?.classList.contains('open')?closeDrawer():openDrawer()};
if(shade)shade.onclick=closeDrawer;$('#mobileDrawerClose')?.addEventListener('click',closeDrawer);
sidebar?.addEventListener('click',e=>{if(e.target.closest('[data-page],#logout'))setTimeout(closeDrawer,0)});
addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});addEventListener('orientationchange',()=>setTimeout(closeDrawer,100));addEventListener('resize',()=>{if(innerWidth>760)closeDrawer()});
closeDrawer();
const style=document.createElement('style');style.textContent=`#mobileDrawerClose{display:none}@media(max-width:760px){html,body{height:auto!important;min-height:100%!important;overflow-x:hidden!important;overflow-y:auto!important;touch-action:pan-y!important}body.mobile-drawer-open{overflow-y:auto!important;position:static!important}#app,#app:not(.hidden){height:auto!important;min-height:100dvh!important;overflow:visible!important}.main{height:auto!important;min-height:100dvh!important;overflow:visible!important;touch-action:pan-y!important}.content{height:auto!important;min-height:calc(100dvh - 150px)!important;overflow:visible!important;touch-action:pan-y!important;overscroll-behavior-y:auto!important}.sidebar{display:flex!important;position:fixed!important;inset:0 auto 0 0!important;height:100dvh!important;max-height:100dvh!important;overflow-y:auto!important;overflow-x:hidden!important;overscroll-behavior:contain!important;transform:translate3d(-105%,0,0)!important;visibility:hidden!important;pointer-events:none!important;z-index:100!important;will-change:transform}.sidebar.open{transform:translate3d(0,0,0)!important;visibility:visible!important;pointer-events:auto!important}.sidebar .brand{position:relative;padding-right:48px!important;flex:0 0 auto}.sidebar>.nav{overflow:visible!important;flex:0 0 auto}.sidebar-bottom{flex:0 0 auto;margin-top:20px!important}#mobileDrawerClose{display:grid;place-items:center;position:absolute;right:2px;top:-6px;width:42px;height:42px;border:0;border-radius:13px;background:rgba(255,255,255,.1);color:#fff;font-size:28px;line-height:1}.mobile-drawer-shade{z-index:90!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;background:rgba(9,28,30,.52)!important}.mobile-app-nav{z-index:80!important}.topbar{z-index:30!important}.table-wrap,html body #app #content .table-wrap{display:block!important;width:100%!important;max-width:100%!important;height:auto!important;max-height:none!important;overflow-x:auto!important;overflow-y:visible!important;touch-action:pan-x pan-y!important;overscroll-behavior-x:contain!important;-webkit-overflow-scrolling:touch!important}table,table#rows{height:auto!important;touch-action:pan-x pan-y!important}.due-toolbar,.due-filters{height:auto!important;max-height:none!important;overflow:visible!important}.due-filters{touch-action:pan-y!important}.panel,.cards,.grid2,.doc-grid,.activity,.admin-stack{height:auto!important;max-height:none!important;overflow:visible}.panel:has(.table-wrap){overflow:hidden!important}.panel:has(.table-wrap) .table-wrap{overflow-x:auto!important;overflow-y:visible!important}.modal-body{overflow-y:auto!important;touch-action:pan-y!important}.mobile-app-nav button{touch-action:manipulation}.mobile-app-nav button:active,.primary:active,.ghost:active{transform:scale(.96)} }`;document.head.appendChild(style);
})();
