(()=>{
  const duePaid=d=>d&&((d.current_due_paid===true)||(d.current_due_paid==null&&d.status==='paid'));
  const gross=d=>Math.max(0,Number(d&&d.previous_debt)||0);
  const paidOld=d=>Math.max(0,Math.min(gross(d),Number(d&&d.previous_debt_paid_amount!=null?d.previous_debt_paid_amount:(d&&d.previous_debt_paid?gross(d):0))||0));
  const oldStatus=d=>gross(d)<=0?'Borç yok':((d.previous_debt_paid===true||paidOld(d)>=gross(d))?'Ödendi':(paidOld(d)>0?'Kısmi ödeme':'Ödenmedi'));
  const trDate=v=>v?new Date(v).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'';
  const left=d=>(duePaid(d)?0:Number(d.amount)||0)+Math.max(0,gross(d)-paidOld(d));
  const months={'01':'Ocak','02':'Şubat','03':'Mart','04':'Nisan','05':'Mayıs','06':'Haziran','07':'Temmuz','08':'Ağustos','09':'Eylül','10':'Ekim','11':'Kasım','12':'Aralık'};

  function localizeMonths(){['fMonth','mPeriodMonth'].forEach(id=>{const s=$('#'+id);if(!s)return;Array.from(s.options).forEach(o=>{if(months[o.value])o.textContent=months[o.value];});});}
  function visibleDues(){const trs=Array.from(document.querySelectorAll('#rows tbody tr:not(.missing-due-row)')),ids=new Set(trs.filter(x=>!x.hidden&&x.dataset.dueId).map(x=>String(x.dataset.dueId)));return ids.size?(data.dues||[]).filter(d=>ids.has(String(d.id))):(data.dues||[]);}
  function rows(){return visibleDues().map(d=>{const p=occupant(d.unit_id),g=gross(d),po=paidOld(d),r=left(d);return{'Villa':unit(d.unit_id),'Sakin':p.full_name||'','Dönem':String(d.period||'').slice(0,7),'Son Ödeme':d.due_date||'','Aidat':Number(d.amount)||0,'Aidat Durumu':duePaid(d)?'Ödendi':'Ödenmedi','Aidat Ödeme Tarihi':duePaid(d)?trDate(d.paid_at):'','Geçmiş Borç':g,'Geçmiş Borç Durumu':oldStatus(d),'Geçmiş Borç Ödeme Tarihi':oldStatus(d)==='Ödendi'?trDate(d.previous_debt_paid_at):'','Geçmiş Borca Ödenen':po,'Kalan Geçmiş Borç':Math.max(0,g-po),'Toplam Kalan Borç':r,'Durum':r<=0?'Ödendi':(duePaid(d)||po>0?'Kısmi ödeme':'Ödenmedi')};});}

  function offer(blob,name,title){const file=new File([blob],name,{type:blob.type});$('#modalRoot').innerHTML='<div class="modal-backdrop"><div class="modal file-delivery-modal"><div class="modal-head"><div><h3>'+esc(title)+'</h3><small>'+esc(name)+'</small></div></div><div class="modal-body"><p>Dosyayı cihazınıza kaydedebilir veya desteklenen uygulamalarla paylaşabilirsiniz.</p></div><div class="modal-foot file-delivery-actions"><button class="ghost" id="cancelFile">Kapat</button><button class="ghost" id="shareFile">Paylaş</button><button class="primary" id="saveFile">Kaydet</button></div></div></div>';$('#cancelFile').onclick=()=>{$('#modalRoot').innerHTML='';};$('#saveFile').onclick=()=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);toast(name+' kaydedildi.');};$('#shareFile').onclick=async()=>{if(!navigator.share||!navigator.canShare||!navigator.canShare({files:[file]}))return toast('Bu cihaz dosya paylaşımını desteklemiyor. Kaydet seçeneğini kullanabilirsiniz.','error');try{await navigator.share({files:[file],title});}catch(e){if(e.name!=='AbortError')toast('Dosya paylaşılamadı.','error');}};}

  function excel(){const list=rows();if(!list.length)return toast('Dışa aktarılacak aidat bulunamadı.','error');const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(list);ws['!cols']=[{wch:12},{wch:24},{wch:11},{wch:13},{wch:12},{wch:16},{wch:22},{wch:14},{wch:22},{wch:26},{wch:22},{wch:20},{wch:20},{wch:16}];XLSX.utils.book_append_sheet(wb,ws,'Aidatlar ve Ödemeler');const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'});offer(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'Asrav_Sitesi_Aidatlar_Odemeler_'+new Date().toISOString().slice(0,10)+'.xlsx','Asrav Sitesi Aidat ve Ödemeleri');}

  async function pdf(){const list=rows();if(!list.length)return toast('Dışa aktarılacak aidat bulunamadı.','error');if(!window.jspdf||!window.jspdf.jsPDF||!window.html2canvas)return toast('PDF bileşeni yüklenemedi.','error');const cols=['Villa','Sakin','Dönem','Son Ödeme','Aidat','Aidat Durumu','Aidat Ödeme Tarihi','Geçmiş Borç','Geçmiş Borç Durumu','Geçmiş Borç Ödeme Tarihi','Geçmiş Borca Ödenen','Kalan Geçmiş Borç','Toplam Kalan Borç','Durum'],moneyCols=new Set(['Aidat','Geçmiş Borç','Geçmiş Borca Ödenen','Kalan Geçmiş Borç','Toplam Kalan Borç']),host=document.createElement('div');host.className='pdf-tr';host.innerHTML='<h1>Asrav Sitesi — Aidat ve Ödeme Listesi</h1><p>Oluşturma: '+esc(new Date().toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'}))+'</p><table><thead><tr>'+cols.map(c=>'<th>'+esc(c)+'</th>').join('')+'</tr></thead><tbody>'+list.map(r=>'<tr>'+cols.map(c=>'<td>'+esc(moneyCols.has(c)?money(r[c]):(r[c]||'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';document.body.appendChild(host);try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;const canvas=await html2canvas(host,{scale:1.5,backgroundColor:'#fff',useCORS:true,logging:false}),doc=new window.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a3'}),ratio=Math.min(400/canvas.width,277/canvas.height);doc.addImage(canvas.toDataURL('image/png'),'PNG',10,10,canvas.width*ratio,canvas.height*ratio,'FAST');offer(doc.output('blob'),'Asrav_Sitesi_Aidatlar_Odemeler_'+new Date().toISOString().slice(0,10)+'.pdf','Asrav Sitesi Aidat ve Ödemeleri');}catch(e){console.error(e);toast('PDF hazırlanamadı. Lütfen tekrar deneyin.','error');}finally{host.remove();}}

  function mount(){localizeMonths();if(page!=='dues')return;const x=$('#exportDuesExcel'),p=$('#exportDuesPdf');if(x)x.onclick=excel;if(p)p.onclick=pdf;}
  const oldRender=render;render=function(){const r=oldRender();mount();return r;};
  const oldModal=modal;modal=function(){const r=oldModal.apply(this,arguments);localizeMonths();return r;};
  const style=document.createElement('style');style.textContent='.pdf-tr{position:fixed;left:-100000px;top:0;width:1600px;padding:28px;background:#fff;color:#173c45;font-family:Arial,"Noto Sans",sans-serif}.pdf-tr h1{margin:0 0 6px;font-size:24px}.pdf-tr p{margin:0 0 16px;font-size:12px}.pdf-tr table{width:100%;border-collapse:collapse}.pdf-tr th{background:#235b5f;color:#fff;font-size:11px;padding:7px 5px;border:1px solid #d5e1df}.pdf-tr td{font-size:10px;padding:6px 5px;border:1px solid #d5e1df;white-space:nowrap}.pdf-tr tbody tr:nth-child(even){background:#f4f8f7}';document.head.appendChild(style);mount();
})();
