(()=>{
  const host=document.getElementById('siteChatbot');if(!host)return;
  const input=host.querySelector('#asravChatInput'),button=host.querySelector('#asravChatSend'),messages=host.querySelector('.asrav-chat-messages'),panel=host.querySelector('.asrav-chat-panel'),localSend=button?.onclick;
  if(!input||!button||!messages||!panel||!localSend)return;
  const history=[];let provider='auto',testerReady=false,voiceEnabled=true,listening=false,pendingFile=null;
  const labels={auto:'Otomatik',notion:'Notion Agent',groq:'Groq',openrouter:'OpenRouter'};
  const add=(text,type)=>{const e=document.createElement('div');e.className='asrav-chat-message '+type;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight;return e};
  const speak=text=>{if(!voiceEnabled||!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text));u.lang='tr-TR';u.rate=.96;u.pitch=1;window.speechSynthesis.speak(u)};
  const controls=document.createElement('div');controls.className='asrav-chat-head-actions';controls.innerHTML='<button class="asrav-chat-sound" aria-label="Sesli yanıtı kapat" title="Sesli yanıt">🔊</button><button class="asrav-chat-expand" aria-label="Pencereyi büyüt" title="Büyüt">⛶</button>';
  const close=host.querySelector('.asrav-chat-close');close?.parentNode?.insertBefore(controls,close);if(close)controls.appendChild(close);
  controls.querySelector('.asrav-chat-expand').onclick=()=>{panel.classList.toggle('expanded');const on=panel.classList.contains('expanded');controls.querySelector('.asrav-chat-expand').textContent=on?'❐':'⛶';controls.querySelector('.asrav-chat-expand').setAttribute('aria-label',on?'Pencereyi küçült':'Pencereyi büyüt')};
  controls.querySelector('.asrav-chat-sound').onclick=()=>{voiceEnabled=!voiceEnabled;if(!voiceEnabled)window.speechSynthesis?.cancel();controls.querySelector('.asrav-chat-sound').textContent=voiceEnabled?'🔊':'🔇';controls.querySelector('.asrav-chat-sound').setAttribute('aria-label',voiceEnabled?'Sesli yanıtı kapat':'Sesli yanıtı aç');add(voiceEnabled?'Sesli yanıt açıldı.':'Sesli yanıt kapatıldı.','system')};
  const footer=host.querySelector('.asrav-chat-panel footer');
  const fileInput=document.createElement('input');fileInput.type='file';fileInput.className='asrav-chat-file-input';fileInput.accept='.txt,.md,.csv,.json,.pdf,image/*';fileInput.hidden=true;
  const fileBtn=document.createElement('button');fileBtn.type='button';fileBtn.className='asrav-chat-tool asrav-chat-file';fileBtn.textContent='📎';fileBtn.title='Dosya ekle';fileBtn.setAttribute('aria-label','Dosya ekle');
  const micBtn=document.createElement('button');micBtn.type='button';micBtn.className='asrav-chat-tool asrav-chat-mic';micBtn.textContent='🎙️';micBtn.title='Konuşarak yaz';micBtn.setAttribute('aria-label','Konuşarak yaz');
  footer.insertBefore(fileBtn,input);footer.insertBefore(micBtn,input);footer.appendChild(fileInput);
  const fileBadge=document.createElement('div');fileBadge.className='asrav-chat-file-badge hidden';footer.parentNode.insertBefore(fileBadge,footer);
  fileBtn.onclick=()=>fileInput.click();
  async function extractFile(file){
    if(file.size>8*1024*1024)throw new Error('Dosya en fazla 8 MB olabilir.');
    const name=file.name||'dosya',type=file.type||'';
    if(type==='application/pdf'||/\.pdf$/i.test(name)){
      if(!window.pdfjsLib)throw new Error('PDF okuyucu yüklenemedi.');
      const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;let text='';
      for(let i=1;i<=Math.min(pdf.numPages,15)&&text.length<7600;i++){const page=await pdf.getPage(i),c=await page.getTextContent();text+='\n'+c.items.map(x=>x.str||'').join(' ')}return text.trim();
    }
    if(type.startsWith('image/')){
      if(!window.Tesseract)throw new Error('Görsel metin okuyucu yüklenemedi.');
      add(name+' içindeki metin okunuyor…','system');const r=await Tesseract.recognize(file,'tur');return String(r?.data?.text||'').trim();
    }
    if(type.startsWith('text/')||/\.(txt|md|csv|json)$/i.test(name))return (await file.text()).trim();
    throw new Error('Bu dosya türü desteklenmiyor. PDF, görsel veya metin dosyası seçin.');
  }
  fileInput.onchange=async()=>{const file=fileInput.files?.[0];if(!file)return;fileBtn.disabled=true;try{const text=await extractFile(file);if(!text)throw new Error('Dosyadan okunabilir metin çıkarılamadı.');pendingFile={name:file.name,text:text.slice(0,7600)};fileBadge.classList.remove('hidden');fileBadge.innerHTML='<span>📎 '+file.name+'</span><button type="button" aria-label="Dosyayı kaldır">×</button>';fileBadge.querySelector('button').onclick=()=>{pendingFile=null;fileInput.value='';fileBadge.classList.add('hidden')};add(file.name+' sohbete eklendi.','system')}catch(e){add(e?.message||'Dosya okunamadı.','error');pendingFile=null;fileInput.value=''}finally{fileBtn.disabled=false}};
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
  if(Recognition){const rec=new Recognition();rec.lang='tr-TR';rec.interimResults=true;rec.continuous=false;let base='',finalText='';micBtn.onclick=()=>{if(listening){rec.stop();return}base=input.value.trim();finalText='';try{rec.start();listening=true;micBtn.classList.add('active');micBtn.textContent='⏹';input.placeholder='Dinleniyor…'}catch{}};rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+t;else interim+=t}input.value=[base,finalText,interim].filter(Boolean).join(' ').trim()};rec.onerror=e=>{if(e.error!=='aborted')add(e.error==='not-allowed'?'Mikrofon izni verilmedi.':'Ses algılanamadı; tekrar deneyin.','error')};rec.onend=()=>{listening=false;micBtn.classList.remove('active');micBtn.textContent='🎙️';input.placeholder='Siteyle ilgili sorunuzu yazın…';input.value=[base,finalText].filter(Boolean).join(' ').trim();if(finalText.trim())button.click()}}else{micBtn.disabled=true;micBtn.title='Bu tarayıcı sesli girişi desteklemiyor'}
  async function enableTester(){try{if(testerReady||host.querySelector('.asrav-ai-testbar'))return;if(typeof db==='undefined')return;const {data:{user}}=await db.auth.getUser();if(!user)return;const {data:p}=await db.from('profiles').select('role,roles').eq('id',user.id).single(),roles=Array.isArray(p?.roles)?p.roles:[];if(p?.role!=='admin'&&!roles.includes('admin'))return;const bar=document.createElement('div');bar.className='asrav-ai-testbar';bar.innerHTML='<label>Model testi</label><select aria-label="Test edilecek yapay zekâ modeli"><option value="auto">Otomatik geçiş</option><option value="notion">Notion Agent</option><option value="groq">Groq (ana)</option><option value="openrouter">OpenRouter (yedek)</option></select><span>Yönetici</span>';host.querySelector('.asrav-chat-suggestions')?.before(bar);bar.querySelector('select').onchange=e=>{provider=e.target.value;add(labels[provider]+' seçildi.','system')};testerReady=true}catch{console.warn('Model test seçicisi açılamadı.')}}
  async function aiSend(){
    const text=input.value.trim();if(!text&&!pendingFile)return;input.value='';const attachment=pendingFile;pendingFile=null;fileInput.value='';fileBadge.classList.add('hidden');
    const shown=(text||'Bu dosyayı incele')+(attachment?'\n📎 '+attachment.name:'');const combined=(text||'Bu dosyayı incele ve özetle.')+(attachment?'\n\n[Dosya: '+attachment.name+']\n'+attachment.text:'');
    const userNode=add(shown,'user'),waiting=add((attachment?'Dosya ve ':provider==='auto'?'Yapay zekâ ':labels[provider]+' ')+'yanıtı hazırlanıyor…','bot');button.disabled=true;
    try{const useNotion=provider==='notion'||!!attachment,functionName=useNotion?'asrav-notion-agent':'asrav-ai-assistant',requestBody=useNotion?{message:combined.slice(0,9000)}:{message:combined.slice(0,500),history:history.slice(-6),provider};const result=await db.functions.invoke(functionName,{body:requestBody}),d=result.data;if(d?.test&&d.success===false){waiting.className='asrav-chat-message error';waiting.textContent=labels[d.provider||provider]+' başarısız: '+(d.diagnostic||d.error||'yanıt alınamadı');return}if(!result.error&&d?.answer){waiting.textContent=d.answer;const badge=document.createElement('small');badge.className='asrav-ai-provider';badge.textContent='Yanıt: '+labels[d.provider||provider];waiting.appendChild(badge);history.push({role:'user',content:text||('[Dosya] '+attachment?.name)},{role:'assistant',content:d.answer});speak(d.answer);return}}catch(e){console.warn('AI sağlayıcısı kullanılamadı.',e)}
    if(provider!=='auto'||attachment){waiting.className='asrav-chat-message error';waiting.textContent=(attachment?'Dosya analizi':'Notion Agent testi')+' sırasında bağlantı hatası oluştu.';return}userNode.remove();waiting.remove();input.value=text;localSend.call(button);add('AI servisleri kullanılamadığı için yerel güvenli yanıt gösterildi.','system')
  }
  button.onclick=async()=>{try{await aiSend()}finally{button.disabled=false}};input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();button.click()}};host.querySelectorAll('.asrav-chat-suggestions button').forEach(b=>b.onclick=()=>{input.value=b.textContent;button.click()});
  const style=document.createElement('style');style.textContent='.asrav-chat-head-actions{display:flex!important;flex-direction:row!important;align-items:center;gap:6px}.asrav-chat-head-actions button{width:34px;height:34px;border:0;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:17px;cursor:pointer}.asrav-chat-panel.expanded{position:fixed;inset:5vh 5vw;width:90vw;height:90vh;max-width:none;border-radius:20px}.asrav-chat-panel footer{grid-template-columns:38px 38px 1fr 42px!important}.asrav-chat-tool{border:1px solid #bfd3cf;border-radius:11px;background:#f5faf9;color:#17666c;font-size:17px;cursor:pointer}.asrav-chat-mic.active{background:#c93636;color:#fff;border-color:#c93636;animation:asravPulse 1s infinite}.asrav-chat-file-badge{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:7px 12px;border-top:1px solid #e2ebe9;background:#eef7f5;color:#28535a;font-size:11px}.asrav-chat-file-badge.hidden{display:none}.asrav-chat-file-badge span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.asrav-chat-file-badge button{border:0;background:transparent;color:#8d3030;font-size:18px}.asrav-ai-testbar{display:flex;align-items:center;gap:6px;padding:7px 10px;border-top:1px solid #dce7e5;background:#f5faf9;font-size:11px}.asrav-ai-testbar label{font-weight:700;color:#28535a}.asrav-ai-testbar select{min-width:0;flex:1;border:1px solid #bfd3cf;border-radius:7px;padding:5px;background:#fff;color:#17383d}.asrav-ai-testbar span,.asrav-ai-provider{color:#64817c;font-size:9px}.asrav-ai-provider{display:block;margin-top:6px;font-weight:700}.asrav-chat-message.system{align-self:center;background:#eef6f5;color:#426862;font-size:10px}.asrav-chat-message.error{background:#fff0f0;color:#9a3030;white-space:pre-wrap}.asrav-chat-message.bot{white-space:pre-wrap}@keyframes asravPulse{50%{transform:scale(1.08);box-shadow:0 0 0 5px rgba(201,54,54,.18)}}@media(max-width:760px){.asrav-chat-panel.expanded{inset:8px;width:auto;height:calc(100dvh - 16px);border-radius:14px}.asrav-chat-panel footer{grid-template-columns:36px 36px 1fr 40px!important;padding:8px!important}}';document.head.appendChild(style);
  enableTester();if(typeof db!=='undefined')db.auth.onAuthStateChange(()=>setTimeout(enableTester,30));else{let tries=0;const t=setInterval(()=>{tries++;if(typeof db!=='undefined'){clearInterval(t);db.auth.onAuthStateChange(()=>setTimeout(enableTester,30));enableTester()}if(tries>40)clearInterval(t)},500)}
})();
